/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 12-ago-2022 10:55:02 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

CREATE DATABASE ProGym;
USE ProGym;

/*CREATE DATABASE ProGym;*/

/*USE ProGym;*/

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Aluno` CASCADE
;

DROP TABLE IF EXISTS `AssociaçãoAdministrativa` CASCADE
;

DROP TABLE IF EXISTS `Atividade` CASCADE
;

DROP TABLE IF EXISTS `Contrato` CASCADE
;

DROP TABLE IF EXISTS `CoordenaçãoDesportiva` CASCADE
;

DROP TABLE IF EXISTS `Filial` CASCADE
;

DROP TABLE IF EXISTS `GestorDeFilial` CASCADE
;

DROP TABLE IF EXISTS `Matricula` CASCADE
;

DROP TABLE IF EXISTS `Pagamento` CASCADE
;

DROP TABLE IF EXISTS `Professor` CASCADE
;

DROP TABLE IF EXISTS `RelatorioDiário` CASCADE
;

DROP TABLE IF EXISTS `Secretária` CASCADE
;

/* Create Tables */

CREATE TABLE `Aluno`
(
	`AlunoID` Integer NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(50) 	 NULL,
    `dataNascimento` DATE NULL,
	`email` VARCHAR(50)  NULL,
    `fotoUrl` VARCHAR(100) NULL,
	CONSTRAINT `PK_Aluno` PRIMARY KEY (`AlunoID` ASC)
)

;

CREATE TABLE `AssociaçãoAdministrativa`
(
	`AssociaçãoAdministrativaID` Integer NOT NULL AUTO_INCREMENT,
    `Descricao` int NULL,
	CONSTRAINT `PK_AssociaçãoAdministrativa` PRIMARY KEY (`AssociaçãoAdministrativaID` ASC)
)

;

CREATE TABLE `CoordenaçãoDesportiva`
(
	`CoordenaçãoDesportivaID` Integer NOT NULL AUTO_INCREMENT,
    `Descricao` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_CoordenaçãoDesportiva` PRIMARY KEY (`CoordenaçãoDesportivaID` ASC)
);


CREATE TABLE `Filial`
(
	`FilialID` Integer NOT NULL AUTO_INCREMENT,
	`Horainicio` Time 	 NULL,
	`Horatermino` Time 	 NULL,
	`Localizacao` VARCHAR(30) NULL,
	`GestorDeFilialID` INTEGER NOT NULL,
    `CoordenaçãoDesportivaID` INTEGER NOT NULL,
	CONSTRAINT `PK_Filial` PRIMARY KEY (`FilialID` ASC)
)

;

CREATE TABLE `Atividade`
(
	`AtividadeID` Integer NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(100) 	 NULL,
	`Descricao` VARCHAR(100) 	 NULL,
    `FilialID` INTEGER NOT NULL,
	`CoordenaçãoDesportivaID` INTEGER NOT NULL,
	`ProfessorID` INTEGER NOT NULL,
	CONSTRAINT `PK_Atividade` PRIMARY KEY (`AtividadeID` ASC)
)

;


CREATE TABLE `Contrato`
(
	`ContratoID` Integer NOT NULL AUTO_INCREMENT,
	`CoordenaçãoDesportivaID` INTEGER 	 NULL,
	`ProfessorID` INTEGER 	 NULL,
	CONSTRAINT `PK_Contrato` PRIMARY KEY (`ContratoID` ASC)
)

;

CREATE TABLE `GestorDeFilial`
(
	`GestorDeFilialID` Integer NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(150) 	 NULL,
	CONSTRAINT `PK_GestorDeFilial` PRIMARY KEY (`GestorDeFilialID` ASC)
)

;

CREATE TABLE `Matricula`
(
	`MatriculaID` Integer NOT NULL AUTO_INCREMENT,
	`Data` TIMESTAMP NULL,
	`Estado` int 	 NULL DEFAULT 1 COMMENT 'O estado da matricula indica se a matricula está em vigor ou cancelada',
    `AlunoID` INTEGER  NOT NULL,
	`AtividadeID` INTEGER  NOT NULL,
    `SecretáriaID` INTEGER NOT NULL,
	CONSTRAINT `PK_Matricula` PRIMARY KEY (`MatriculaID` ASC)
)

;

CREATE TABLE `Pagamento`
(
	`PagamentoID` Integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Data` TIMESTAMP NULL,
	`Taxa` DOUBLE 	 NULL,
	`Valor` DOUBLE 	 NULL,
	`CodigoRecibo` VARCHAR(200) NULL,
    `Banco`VARCHAR(50) NULL,
	`AlunoID` INTEGER 	 NULL,
	`MatriculaID` INTEGER 	 NULL,
    `CobrancaID` INTEGER NOT NULL,
	`SecretáriaID` INTEGER NOT NULL
)

;

CREATE TABLE `Professor`
(
	`ProfessorID` Integer NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Professor` PRIMARY KEY (`ProfessorID` ASC)
)

;

CREATE TABLE `RelatorioDiário`
(
	`RelatorioDiárioID` Integer NOT NULL AUTO_INCREMENT,
	`Datadeemissao` Date 	 NULL,
	`Horadeemissao` Time 	 NULL,
	`Matriclulascanceladas` int 	 NULL,
	`Matriculasefetuadas` int 	 NULL,
	`Origem` int NULL,
	`Vagasdisponiveis` int 	 NULL,
	`GestorDeFilialID` INTEGER 	 NULL,
	CONSTRAINT `PK_RelatorioDiário` PRIMARY KEY (`RelatorioDiárioID` ASC)
)


;

CREATE TABLE `Secretária`
(
	`SecretáriaID` Integer NOT NULL auto_increment,
	`email` VARCHAR(100) NOT NULL,
    `senha` VARCHAR(100) NOT NULL,
	`Nome` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Secretária` PRIMARY KEY (`SecretáriaID` ASC)
)

;

/*
SELECT * FROM `Secretária`;
UPDaTE `Secretária`SET email = 'atija@gmail.com' WHERE `SecretáriaID` >= 1;
*/

CREATE TABLE Cobranca
(
	`CobrancaID` INTEGER NOT NULL AUTO_INCREMENT,
    `DataInicio` TIMESTAMP NULL,
    `DataTermino` TIMESTAMP NULL,
    `MatriculaID` INTEGER NOT NULL,
    `Taxa` FLOAT NOT NULL DEFAULT 0,
    `Valor` FLOAT NOT NULL,
    `Pago` BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT `PK_Cobranca` PRIMARY KEY (`CobrancaID` ASC) 
)
;


/*CREATE TABLE Usu*/

/* Create Foreign Key Constraints */

ALTER TABLE `Aluno` 
 ADD CONSTRAINT `UQ_Aluno_Nome_Email`
	UNIQUE (`email`);
;

ALTER TABLE `Aluno` 
 ADD CONSTRAINT `UQ_Aluno_Tudo`
	UNIQUE (`Nome`, `Email`, `DataNascimento`);
;

ALTER TABLE `Atividade` 
 ADD CONSTRAINT `FK_Atividade_Realiza`
	FOREIGN KEY (`FilialID`) REFERENCES `Filial` (`FilialID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Atividade` 
 ADD CONSTRAINT `FK_Atividade_Define_1`
	FOREIGN KEY (`CoordenaçãoDesportivaID`) REFERENCES `CoordenaçãoDesportiva` (`CoordenaçãoDesportivaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Filial` 
 ADD CONSTRAINT `FK_Atividade_Define`
	FOREIGN KEY (`CoordenaçãoDesportivaID`) REFERENCES `CoordenaçãoDesportiva` (`CoordenaçãoDesportivaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Atividade` 
 ADD CONSTRAINT `FK_Atividade_Professor`
	FOREIGN KEY (`ProfessorID`) REFERENCES `Professor` (`ProfessorID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Contrato` 
 ADD CONSTRAINT `FK_Contrato_Coordenação Desportiva`
	FOREIGN KEY (`CoordenaçãoDesportivaID`) REFERENCES `CoordenaçãoDesportiva` (`CoordenaçãoDesportivaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Contrato` 
 ADD CONSTRAINT `FK_Contrato_Professor`
	FOREIGN KEY (`ProfessorID`) REFERENCES `Professor` (`ProfessorID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Filial` 
 ADD CONSTRAINT `FK_Filial_Gere`
	FOREIGN KEY (`GestorDeFilialID`) REFERENCES `GestorDeFilial` (`GestorDeFilialID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Matricula` 
 ADD CONSTRAINT `FK_Matricula_Aluno`
	FOREIGN KEY (`AlunoID`) REFERENCES `Aluno` (`AlunoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Matricula` 
 ADD CONSTRAINT `FK_Matricula_Atividade`
	FOREIGN KEY (`AtividadeID`) REFERENCES `Atividade` (`AtividadeID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Matricula` 
 ADD CONSTRAINT `FK_Matricula_Secretária`
	FOREIGN KEY (`SecretáriaID`) REFERENCES `Secretária` (`SecretáriaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Matricula` 
 ADD CONSTRAINT `UQ_Matricula_Ano` UNIQUE(`AlunoID`, `AtividadeID`);
;

ALTER TABLE `Pagamento` 
 ADD CONSTRAINT `FK_Pagamento_Aluno`
	FOREIGN KEY (`AlunoID`) REFERENCES `Aluno` (`AlunoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pagamento` 
 ADD CONSTRAINT `FK_Pagamento_Matricula`
	FOREIGN KEY (`MatriculaID`) REFERENCES `Matricula` (`MatriculaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pagamento` 
 ADD CONSTRAINT `FK_Pagamento_Cobranca`
	FOREIGN KEY (`CobrancaID`) REFERENCES `Cobranca` (`CobrancaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pagamento` 
 ADD CONSTRAINT `FK_Pagamento_Secretária`
	FOREIGN KEY (`SecretáriaID`) REFERENCES `Secretária` (`SecretáriaID`) ON DELETE No Action ON UPDATE No Action
;
 
ALTER TABLE `Pagamento` 
	ADD CONSTRAINT `UQ_Pagamento_Cobranca` UNIQUE (`CobrancaID`)
;

ALTER TABLE `RelatorioDiário` 
 ADD CONSTRAINT `FK_Relatorio Diário_Emite`
	FOREIGN KEY (`GestorDeFilialID`) REFERENCES `GestorDeFilial` (`GestorDeFilialID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `RelatorioDiário` 
 ADD CONSTRAINT `FK_Relatorio Diário_Emite_2`
	FOREIGN KEY (`Origem`) REFERENCES `Filial` (`GestorDeFilialID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Cobranca` 
 ADD CONSTRAINT `FK_Cobranca_Matricula`
	FOREIGN KEY (`MatriculaID`) REFERENCES `Matricula` (`MatriculaID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
